# Generated by Django 4.2.26 on 2025-12-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sessionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
