# Generated by Django 4.2.26 on 2025-12-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studysession_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrsvp',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
